### PR TITLE
65 move agent front end to oasis ecosystem

### PR DESCRIPTION
**Pull request by tsearle**
get oasis-frontend in oasis, and docker

### CODE REVIEW

**Review by gabriel0003 — APPROVED** [review]

**Review by edifirut — APPROVED** [review]

**Comment by mattbr0wn** [comment]
@all-contributors please add @tsearle for code

**Comment by mattbr0wn** [comment]
@all-contributors please add @tsearle for docs

**Comment by mattbr0wn** [comment]
@all-contributors please add @gabriel0003 for code @gabriel0003 for review @edifirut for review

**Comment by mattbr0wn** [comment]
@all-contributors please add @edifirut for review

**Pull request merged**
